version: "3"

services:
  backend:
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=prod
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 3200:3200
    links:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - 27018:27017
    logging:
      driver: "none"